GET http://localhost:3000/user/

###

POST http://localhost:3000/user/userSignUp
Content-Type: application/json

{
    "firstName": "Abc",
    "lastName": "De",
    "email": "teahoo.com",
    "password": "4532DS"
}

###

GET http://localhost:3000/user/login/
Content-Type: application/json

{
    "email": "test@yahoo.com",
    "password": "4532DS"
}