GET http://localhost:3000/user/

###

POST http://localhost:3000/user/userSignUp
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email": "adminf@yahoo.com",
    "password": "Password123"
}

###

GET http://localhost:3000/user/login/
Content-Type: application/json

{
    "email": "admintwo@yahoo.com",
    "password": "Password123"
}


###
POST http://localhost:3000/notes/addNotes
Content-Type: application/json

{
    "title": "First Note",
    "description": "Lorem Ipsum"
}


###
POST http://localhost:3000/notes/addNotes
Content-Type: application/json

{
    "title": "First Note",
    "description": "Lorem DIpsum",
    "color": "#FFFFFF"
}

###
GET http://localhost:3000/notes/getNotesList


###

PATCH http://localhost:3000/notes/deleteNote/6138d5294dbaec63e2a81c8f

###

PATCH http://localhost:3000/notes/archiveNote/613747deaf5f201cb73364d2

###
GET http://localhost:3000/user/getAllUsers
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWludHdvQHlhaG9vLmNvbSIsInBhc3N3b3JkIjoiUGFzc3dvcmQxMjMiLCJpYXQiOjE2MzE1ODI1NTN9.KmHcsiBHNHDSWVC3gn-8BLDil29afIJXF7--H9ctFto